#!/bin/bash



 List all files in the current directory, including hidden files

ls -la



 Change directory to the parent of the current directory

cd ..



 List all files in the parent directory, including hidden files

ls -la



 Change directory to the /boot directory

cd /boot



 List all files in the /boot directory, including hidden files

ls -la


